version: '3.5'
services:
  solr:
    image: 'solr'
    container_name: 'solr-storage'
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command: 
      - solr-precreate
      - jobs
  api:
    image: $API_IMAGE
    container_name: $API_CONTAINER
    restart: on-failure
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - "${API_VOLUME}"
    depends_on:
      - solr

networks:
  default:
    name: $NETWORK

volumes:
  data: